name: unlimited_tools
description: command line tools for some templated generation in your projects
version: 0.1.1
homepage: https://github.com/crifurch/unlimited_tools

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  args: ^2.3.2
  unlimited_things_dart: ^0.0.1
  sprintf: ^7.0.0
  meta: ^1.8.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.2

executables:
  unlimited_tools: unlimited_tools
